* Encoding: UTF-8.


* SPSS CHAPTER 8

* Table 8.4

DATASET ACTIVATE DataSet1.
FREQUENCIES VARIABLES=smoker
  /ORDER=ANALYSIS.

* Table 8.5

DESCRIPTIVES VARIABLES=educ age income pcigs79 smoker
  /STATISTICS=MEAN STDDEV MIN MAX.


* Table 8.6

SUMMARIZE
  /TABLES=educ age income pcigs79 BY smoker
  /FORMAT=NOLIST TOTAL
  /TITLE='Case Summaries'
  /MISSING=VARIABLE
  /CELLS=COUNT MEAN STDDEV.


* Table 8.7 and Figure 8.27


REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN 
  /DEPENDENT smoker
  /METHOD=ENTER educ age income pcigs79.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN 
  /DEPENDENT smoker
  /METHOD=ENTER educ age pcigs79 inc_10k.

* Table 8.9 and 8.10 and Figure 8.29

LOGISTIC REGRESSION VARIABLES smoker
  /METHOD=ENTER educ age income pcigs79 
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).


LOGISTIC REGRESSION VARIABLES smoker
  /METHOD=ENTER educ age pcigs79 inc_10k 
  /CRITERIA=PIN(.05) POUT(.10) ITERATE(20) CUT(.5).

* Figure 8.9 and  8.31

* Generalized Linear Models.
GENLIN smoker (REFERENCE=0) WITH educ age inc_10k pcigs79
  /MODEL educ age inc_10k pcigs79 INTERCEPT=YES
 DISTRIBUTION=BINOMIAL LINK=PROBIT
  /CRITERIA METHOD=FISHER(1) SCALE=1 COVB=MODEL MAXITERATIONS=100 MAXSTEPHALVING=5 
    PCONVERGE=1E-006(ABSOLUTE) SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 CITYPE=WALD 
    LIKELIHOOD=FULL
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.

* Table 8.16/ Figure 8.20

DATASET ACTIVATE DataSet2.
PROBIT n_transit OF n_trips WITH hh_autos hh_size d_cbd
  /LOG NONE
  /MODEL LOGIT
  /PRINT NONE
  /CRITERIA ITERATE(20) STEPLIMIT(.1).

* Figure 8.25

DATASET ACTIVATE DataSet1.
GRAPH
  /HISTOGRAM=age
  /PANEL ROWVAR=smoker ROWOP=CROSS.
